config/routes.rb
Datafeeds::Application.routes.draw do

  root :to => "pages#dashboard"

  match "/help" => 'pages#help'

  get "leads/index"

  get "leads/show"

  get "leads/edit"

  get "leads/update"

  match "/statistics" => 'pages#sendData'

  match "/clicks" => 'clicks#create'

  post "/notifications/settings_update"


  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
  }

  resources :sites

  resources :feeds do
    collection do
      match "/own" => 'feeds#own_feeds'
      match "/categories/:id" => 'feeds#categories'
      put 'update_fields'
      get 'fields/:id' => 'feeds#fields'
      match '/filter' => 'feeds#filter'
    end
    resources :products
  end 


  resources :products do
    collection do
      match "/export" => 'products#export'
    end
  end


  get "notifications/settings"
  put "notifications/settings_update"

  namespace :admin do
      resources :users
  end

end

app/models/feed.rb
class Feed < ActiveRecord::Base

	require 'nokogiri'
	require 'open-uri' 

	has_many :products
	has_many :feednodes, :autosave => true
	has_many :foreign_categories, :dependent => :delete_all

	attr_accessible :name, :url, :xml_path, :feed_path, :interval_in_seconds, :last_parse, :method_type, :filename, :feednodes_attributes
	accepts_nested_attributes_for :feednodes, :allow_destroy => true
	has_attached_file :filename

	validates :name, :presence => true
	validates :interval_in_seconds, :presence => true

	# File validations
	validates_attachment_presence :filename, :unless => :url
	validates_attachment_content_type :filename, :content_type => 'text/xml', :message => 'Moet een XML bestand zijn'
	validates_attachment_size :filename, :less_than => 100.megabytes, :message => 'Moet kleiner zijn dan 100 MB'

	RECORDS = Hash.new

	
	def parse_feed
		self.last_parse = Time.now
		self.save

		category_key =  Feednode.find(:first, :conditions => {:feed_id => self.id, :field_id => Field.find_by_name('category')})
		producthash_key = Feednode.find(:first, :conditions => {:feed_id => self.id, :field_id => Field.find_by_name('unique hash')})

		if producthash_key
			if self.feed_path == nil
				if !self.url.blank?
					open_uri_fetched = open(self.url)
					doc = Nokogiri::XML(open(open_uri_fetched))
				else
					self.status = 'NoFile'
					self.save
				end
			else
				f = File.open(self.feed_path)
					doc = Nokogiri::XML(f)
				f.close
			end

			if category_key 

				foreign_categories = Array.new
				doc.xpath(self.xml_path+'/'+category_key.name).each do |node|
				    foreign_categories << node.text
				end

				if foreign_categories.count > 0
					foreign_categories.uniq.each do |category|
						if !ForeignCategory.find(:first, :conditions => {:feed_id => self.id, :name => category})	
						  newkey = ForeignCategory.new
						  newkey.feed_id = self.id
						  newkey.name = category
						  newkey.save
						end
					end
				end

			end	

			products = Array.new
			product_categories = ForeignCategory.find(:all, :conditions => {:feed_id => self.id})
			records = Feednode.where('field_id <> ?', Field.where('name' => 'dont use').first)
			doc.xpath(self.xml_path).each do |product|
		       	productdata = Hash.new
				records.each do |record|
					if record.field.name == 'category'	
						category = product_categories.find { |key| key[:name] == product.xpath(record.name).text}
						productdata[:category_id] = category[:id]
					else
						productdata[record.field.product_column_name.to_sym] = product.xpath(record.name).text
					end
				end
				productdata[:feed_id] = self.id
				productdata[:user_id] = self.user_id
				products << productdata
			end


			existing_product_hashes = Product.find(:all, :conditions => {:feed_id => self.id}, :select => "id").map{|p| p.id}
			
			products.each do |product|
				existing_product = Product.find_or_create_by_feed_id_and_unique_hash(self.id, product[:unique_hash])
				existing_product.update_attributes(product)
				existing_product_hashes.delete(existing_product.id)
			end
			Product.update_all({:status => 'inactive'}, {:id => existing_product_hashes})
		end	
	end

	def map_feed
		if self.feed_path == nil
			if !self.url.blank?
				open_uri_fetched = open(self.url).read
				doc = Nokogiri::XML(open_uri_fetched)
			end
		else
			f = File.open(self.feed_path)
				doc = Nokogiri::XML(f)
			f.close
		end

		product_value = 0
	    product_path = nil

	    self.fetch_node_name(doc.xpath("./*").first)

	    RECORDS.each do |record|
	      if product_value < record[1]['count']
	        product_value = record[1]['count']
	        product_path  = record[1]['path']+'/'+record[0]
	      end
	    end

	    self.xml_path = product_path
	    self.save

		foreign_keys = Array.new
			doc.xpath(self.xml_path+"/*").each do |node|
		    foreign_keys << node.name
		end

		foreign_keys.uniq.each do |key|
			if !Feednode.find(:first, :conditions => {:feed_id => self.id,:name => key})
				newkey = Feednode.new
				newkey.feed_id = self.id
				newkey.name = key
				newkey.save
			end
		end

		self.status = 'user_fields'
		self.save

	end

	def fetch_node_name(node, depth = 0)
		sub_nodes = node.xpath("./*")
		if sub_nodes.length > 1
			if RECORDS[node.name].blank?
			  RECORDS[node.name] = Hash.new
			  RECORDS[node.name]['count'] = 1
			  RECORDS[node.name]['path'] = node.parent.path()
			else 
			  RECORDS[node.name]['count'] += 1
			end
		end
		sub_nodes.map { |n| self.fetch_node_name(n, depth+1) } if sub_nodes.length > 0
	end



end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  require 'rubygems'
  require 'nokogiri'
  # Authorisation
  load_and_authorize_resource


  before_filter :authenticate_user!

  def new
    notification = Notification.new
    notification.user_id = params[:user_id]
    notification.message = "U heeft een nieuwe click ontvangen."
    notification.url = nil
    notification.save
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(params[:feed])
    
    if params[:feed][:filename]
      file = params[:feed][:filename]
      directory = "public/uploads/"
      tmp = params[:feed][:filename].tempfile
      file = File.join(directory, params[:feed][:filename].original_filename)
      FileUtils.cp tmp.path, file
      @feed.feed_path = file
    end
    @feed.user_id = current_user.id
    @feed.status = 'created'  

    respond_to do |format|
      if @feed.save
        @feed.delay.map_feed
        format.html { redirect_to own_feeds_path, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def fields
   @feed = Feed.where({:status => ['user_fields', 'active'], :id => params[:id]}).last
   @fields = Field.all
  end

  def update_fields
    @feed = Feed.find(params[:id])
    @fields = Field.all
    @feed.status = 'active'
    @feed.delay.parse_feed
    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to own_feeds_path, :id => @feed.id}
        format.json { head :no_content }
      else
        format.html { render action: "fields" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def categories
    @feed = Feed.where({:status => 'active', :id => params[:id]}).last   
    if @feed
      @foreign_categories = ForeignCategory.where(:feed_id => @feed.id)  
      @categories = Category.all    
      if params[:commit]
        params[:categories].each do |key, value|    
          newkey = ForeignCategory.where({:name => key, :feed_id => @feed.id}).last
          newkey.category_id = value
          newkey.save
        end   
        #XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        #XXXXX DELETE IN PRODUCTION XXXXX
        #XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        @feed.delay.parse_feed
        #XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        redirect_to own_feeds_path, notice: 'Categories where successfully saved.'   
      end
    else
      redirect_to own_feeds_path, notice: 'Categorien kunnen niet worden aangepast.' 
    end
  end

  def index
      @feeds = Feed.find(:all, :conditions => {:status => 'active'}) 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  def own_feeds
    @feeds = Feed.find(:all, :conditions => {:user_id => current_user.id}) 
    respond_to do |format|
      format.html { render action: "index"}
      format.json { render json: @feeds }
    end
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to own_feeds_path, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to own_feeds_path }
      format.json { head :no_content }
    end
  end

  def filter
    @feed_id = params[:id]
    if @feed_id
      if params[:commit]
        filter = Filter.new
        filter.save

        params[:fields].each do |field|
          option = Filteroption.new 
          option.name = 'field'
          option.value = field[0]
          option.filter_id = filter.id
          option.save
        end

        params[:categories].each do |category|
          option = Filteroption.new 
          option.name = 'category'
          option.value = category[0]
          option.filter_id = filter.id
          option.save
        end

        redirect_to :controller => :products, :action => :export, :format => :xml, :id => @feed_id,:user_id => current_user.id, :filter => filter.id
      else
        @categories = Array.new
        @products = Product.where('feed_id' => @feed_id)
        @products.each do |product|
          if !product.category.blank?
            @categories << product.category.name
          end
        end
        @categories = @categories.uniq
        @fields = Field.all
      end
    else
      redirect_to :controller => :feeds, :action => :index
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/categories.html.haml
= form_tag do
  - @foreign_categories.each do |feed_key| 
    .item
      = label_tag feed_key.name
      = select_tag('categories['+feed_key.name+']', options_from_collection_for_select(@categories, "id", "name"))
  = submit_tag "submit"

app/views/feeds/edit.html.haml
= form_for @feed, :html => {:multipart => true} do |f|

  .textfield
    = f.label :name
    = f.text_field  :name
  .select
    = f.label  :interval_in_seconds
    = f.select(:interval_in_seconds, options_for_select([['12 uur', '43200'],['24 uur', '86400'],['48 uur', '172800'], ['72 uur', '199200']]))
  .radio-area
    = label_tag :type_use_file 
    .radio
      = radio_button_tag :type, :use_url, true
      = label_tag :type_use_url 
    .radio 
      = radio_button_tag :type, :use_file 
      = label_tag :type_use_file
  .textfield.url
    = f.label  :url
    = f.text_field :url
  .fieldfield.file.hidden
    = label_tag :file
    = file_field_tag :file

  = submit_tag "Inlezen"

app/views/feeds/fields.html.haml
= form_for @feed, :url => {:action => :update_fields, :id => @feed.id}, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend Feed velden
    = f.fields_for :feednodes do |d|
      .control-group
        = label_tag d.object.name, nil, :class => 'control-label'
        .controls
          %span.hide.options= d.select(:field_id, options_from_collection_for_select(@fields, "id", "name", d.object.field_id))
          %a.btn.btn-small.btn-primary{ :onclick => 'toggleField(this)' }
            %i.icon-white.icon-plus
            %span= t('feeds.fields.use_field')
    .form-actions
      = f.submit t(:add_fields), :class => 'btn btn-primary'

app/views/feeds/filter.html.erb
<%= form_tag :id => @feed_id do %>
	<h1>Sorteer op Categorien</h1>
	<% @categories.each do |category| %>
		<div>
			<%= check_box_tag "categories["+category+"]", nil, true %>
			<%= category %>
		</div>
	<% end %>

	<h1>Sellecteer velden</h1>
	<% @fields.each do |field| %>
	  	<div>
			<%= check_box_tag "fields["+field.name+"]", nil, true %>
			<%= field.name %>
		</div>
	<% end %>
    <%= submit_tag "filtreren" %>
<% end %>

app/views/feeds/index.html.haml
%h2= t('feeds.index_own.title')

%fieldset
  %legend= t('feeds.index_own.list_feeds')
 
%table.table.table-hover.table-striped
  %thead
    %tr
      %th= t('feeds.index_own.name')
      %th= t('feeds.index_own.category')
      %th
      %th
      %th
      %th
      %th

  %tbody
    - @feeds.each do |feed|
      %tr
        %td
          = feed.name
        - if can? :read, @feeds
          - if feed.status == 'user_fields' || feed.status == 'active'
            %td
              = link_to t('feeds.index_own.fields'), :action => 'fields', :id => feed.id
          - else
            %td
          - if feed.status == 'active'
            %td
              = link_to t('feeds.index_own.categories'), :action => 'categories', :id => feed.id
            %td
              = link_to t('feeds.index_own.download'), :controller => 'products', :action => 'export', :id => feed.id, user_id: current_user.id, :format => :xml 
            %td
              = link_to t('feeds.index_own.segment'), :action => 'filter', :id => feed.id
          - else
            %td
            %td
            %td
          %td
          %td{ :style => 'padding:4px' }
            = form_tag feed, :method => :delete, :style => 'margin: 0' do
              .btn-group.pull-right
                = link_to edit_feed_path(feed), :class => 'btn btn-small' do
                  %i.icon-pencil
                %button{ :onclick => "return confirm('#{t('feeds.index_own.delete_confirm')}')", :class => 'btn btn-danger btn-small' }
                  %i.icon-white.icon-trash
  %tfoot
    %tr
      %td{ :colspan => 7 }
        = link_to new_feed_path, :class => 'btn btn-small btn-primary' do
          %i.icon-white.icon-plus
          = t('feeds.index_own.add_feed')

app/views/feeds/index_own.html kopie.haml
%h2= t('feeds.index_own.title')

%fieldset
  %legend= t('feeds.index_own.list_feeds')
 
%table.table.table-hover
  %thead
    %tr
      %th= t('feeds.index_own.name')
      %th= t('feeds.index_own.category')
      %th
      %th
      %th
      %th
      %th

  %tbody
    - @feeds.each do |feed|
      %tr
        %td
          = feed.name
        - if can? :read, @feeds
          - if feed.status == 'user_fields' || feed.status == 'active'
            %td
              = link_to t('feeds.index_own.fields'), :action => 'fields', :id => feed.id
          - else
            %td
          - if feed.status == 'active'
            %td
              = link_to t('feeds.index_own.categories'), :action => 'categories', :id => feed.id
            %td
              = link_to t('feeds.index_own.download'), :controller => 'products', :action => 'export', :id => feed.id, user_id: current_user.id, :format => :xml 
            %td
              = link_to t('feeds.index_own.segment'), :action => 'filter', :id => feed.id
          - else
            %td
            %td
            %td
          %td
          %td
            = form_tag feed, :method => :delete, :style => 'margin-bottom: 0' do
              .btn-group

                = submit_tag t('feeds.index_own.delete'), :onclick => "return confirm('#{t('feeds.index_own.delete_confirm')}')", :class => 'btn btn-danger btn-small'

= link_to new_feed_path, :class => 'btn btn-primary' do
  %i.icon-white.icon-plus
  = t('feeds.index_own.add_feed')

app/views/feeds/index_own.html.haml
%h2= t('feeds.index_own.title')

%fieldset
  %legend= t('feeds.index_own.list_feeds')
 
%table.table.table-hover.table-striped
  %thead
    %tr
      %th= t('feeds.index_own.name')
      %th= t('feeds.index_own.category')
      %th
      %th
      %th
      %th
      %th

  %tbody
    - @feeds.each do |feed|
      %tr
        %td
          = feed.name
        - if can? :read, @feeds
          - if feed.status == 'user_fields' || feed.status == 'active'
            %td
              = link_to t('feeds.index_own.fields'), :action => 'fields', :id => feed.id
          - else
            %td
          - if feed.status == 'active'
            %td
              = link_to t('feeds.index_own.categories'), :action => 'categories', :id => feed.id
            %td
              = link_to t('feeds.index_own.download'), :controller => 'products', :action => 'export', :id => feed.id, user_id: current_user.id, :format => :xml 
            %td
              = link_to t('feeds.index_own.segment'), :action => 'filter', :id => feed.id
          - else
            %td
            %td
            %td
          %td
          %td{ :style => 'padding:4px' }
            = form_tag feed, :method => :delete, :style => 'margin: 0' do
              .btn-group.pull-right
                = link_to edit_feed_path(feed), :class => 'btn btn-small' do
                  %i.icon-pencil
                %button{ :onclick => "return confirm('#{t('feeds.index_own.delete_confirm')}')", :class => 'btn btn-danger btn-small' }
                  %i.icon-white.icon-trash
  %tfoot
    %tr
      %td{ :colspan => 7 }
        = link_to new_feed_path, :class => 'btn btn-small btn-primary' do
          %i.icon-white.icon-plus
          = t('feeds.index_own.add_feed')

app/views/feeds/new.html.haml
= form_for @feed, :html => {:multipart => true, :class => 'form-horizontal', :data => 'feed'} do |f|

  %fieldset
    %legend
      = t('feeds.new.title')
    .control-group
      = f.label t('feeds.new.name'), :class => 'control-label'
      .controls
        = f.text_field :name
    .control-group
      = f.label t('feeds.new.interval_in_seconds'), :class => 'control-label'
      .controls
        = f.select(:interval_in_seconds, options_for_select([['12 uur', '43200'],['24 uur', '86400'],['48 uur', '172800'], ['72 uur', '199200']]))
    .control-group
      = f.label t('feeds.new.type_use_file'), :class => 'control-label'
      .controls
        .btn-group{ 'data-toggle' => 'buttons-radio', 'data-target' => 'method_type' }
          %button{ :type => 'button', :class => 'btn btn-small', :value => 'use_url' }
            = t('feeds.new.url')
          %button{ :type => 'button', :class => 'btn btn-small', :value => 'use_file' }
            = t('feeds.new.file')
        = f.hidden_field :method_type
    .control-group.hide.use_url
      = f.label t('feeds.new.url'), :class => 'control-label'
      .controls
        = f.text_field :url
    .control-group.hide.use_file
      = f.label t('feeds.new.file'), :class => 'control-label'
      .controls
        = file_field(:feed, :filename)
    .form-actions
      = submit_tag t('feeds.new.submit'), :class => 'btn btn-primary'