config/routes.rb
Datafeeds::Application.routes.draw do

  root :to => "pages#dashboard"

  match "/help" => 'pages#help'

  get "leads/index"

  get "leads/show"

  get "leads/edit"

  get "leads/update"

  match "/statistics" => 'pages#sendData'

  match "/clicks" => 'clicks#create'

  post "/notifications/settings_update"


  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
  }

  resources :sites

  resources :feeds do
    collection do
      match "/own" => 'feeds#own_feeds'
      match "/categories/:id" => 'feeds#categories'
      put 'update_fields'
      get 'fields/:id' => 'feeds#fields'
      match '/filter' => 'feeds#filter'
    end
    resources :products
  end 


  resources :products do
    collection do
      match "/export" => 'products#export'
    end
  end


  get "notifications/settings"
  put "notifications/settings_update"

  namespace :admin do
      resources :users
  end

end

app/models/site.rb
class Site < ActiveRecord::Base

  belongs_to :user
  before_validation :check_url

  attr_accessible :name, :url, :description, :category_id, :active, :status, :user_id

  validates :name, :presence => true
  validates_format_of :url, :with => URI::regexp

  # Check if url has http or https prefix
  def check_url
    u = URI.parse(self.url)
	if(!u.scheme)
	    # prepend http:// and try again
	    self.url = "http://#{self.url}"
	    #Edited url
	    return self.url
	elsif(%w{http https}.include?(u.scheme))
	    #Good url
	    return self.url
	else
		#False url
		return false
	end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!

	def index
		@user = User.find(current_user.id)
		@sites = @user.sites
	end

	def new
		@site = Site.new
	end

	def create
		params[:site][:user_id] = current_user.id
		@site = Site.new(params[:site])

	    respond_to do |format|
	      if @site.save
	        format.html { redirect_to sites_path, notice: 'Site is aangemeld.' }
	        format.json { render json: @site, status: :created, location: @site }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @site.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def edit
		@site = Site.find_by_user_id(current_user.id)
	end

	def update
		@site = Site.find(params[:id])

		respond_to do |format|  
	        if @site.update_attributes(params[:site])
	          format.html { redirect_to :back, notice: 'Site was successfully updated.' }
	          format.json { head :no_content }
	        else
	          format.html { render action: "edit" }
	          format.json { render json: @sites.errors, status: :unprocessable_entity }
	        end
		end
    end

    def destroy
      @site = Site.find(params[:id])
      @site.destroy

      respond_to do |format|
        format.html { redirect_to sites_path }
        format.json { head :no_content }
      end
  end
end

app/views/sites/edit.html.haml
%h2= t('labels.editsite')

= form_for(@site) do |s|
  %div
    = s.label :name, t('labels.sitename')
    = s.text_field :name
    = s.label :url, t('labels.url')
    = s.text_field :url
    = s.label :category_id, t('labels.websitecategory')
    = s.collection_select :category_id, Category.all, :id, :name
    = s.label :active, t('labels.active')
    = s.check_box :active
  = s.submit t('labels.editsite')

app/views/sites/index.html.haml
%h2 Sites

%fieldset
  %legend Overzicht sites

  %table.table.table-hover.table-striped
    %thead
      %tr
        %th Naam
        %th URL
        %th
    %tbody
      - @sites.each do |t|
        %tr
          %td= t.name
          %td
            = link_to t.url, t.url
          %td{ :style => 'padding:4px' }
            = form_tag t, :method => :delete, :style => 'margin: 0' do
              .btn-group.pull-right
                = link_to edit_site_path(t), :class => 'btn btn-small' do
                  %i.icon-pencil
                %button{ :onclick => 'return confirm("Are you sure?")', :class => 'btn btn-danger btn-small' }
                  %i.icon-white.icon-trash
    %tfoot
      %tr
        %td{ :colspan => 3 }
          = link_to new_site_path, :class => 'btn btn-small btn-primary' do
            %i.icon-white.icon-plus
            Add Site

app/views/sites/new.html.haml
= form_for @site, :html => { :class => 'form-horizontal' } do |s|
  %fieldset
    %legend= t('labels.newsite')

    .control-group
      = s.label :name, t('labels.sitename'), :class => 'control-label'
      .controls
        = s.text_field :name, :class => 'input-large'
    .control-group
      = s.label :url, t('labels.url'), :class => 'control-label'
      .controls
        = s.text_field :url, :class => 'input-large'
    .control-group
      = s.label :category_id, t('labels.websitecategory'), :class => 'control-label'
      .controls
        = s.collection_select :category_id, Category.all, :id, :name
    .control-group
      = s.label :description, t('labels.description'), :class => 'control-label'
      .controls
        = s.text_area :description, :cols => "40", :rows => "6", :class => 'input-xxlarge'
    .form-actions
      = s.submit 'Opslaan', :class => 'btn btn-primary'