config/routes.rb
Datafeeds::Application.routes.draw do

  root :to => "pages#dashboard"

  match "/help" => 'pages#help'

  get "leads/index"

  get "leads/show"

  get "leads/edit"

  get "leads/update"

  match "/statistics" => 'pages#sendData'

  match "/clicks" => 'clicks#create'

  post "/notifications/settings_update"


  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
  }

  resources :sites

  resources :feeds do
    collection do
      match "/own" => 'feeds#own_feeds'
      match "/categories/:id" => 'feeds#categories'
      put 'update_fields'
      get 'fields/:id' => 'feeds#fields'
      match '/filter' => 'feeds#filter'
    end
    resources :products
  end 


  resources :products do
    collection do
      match "/export" => 'products#export'
    end
  end


  get "notifications/settings"
  put "notifications/settings_update"

  namespace :admin do
      resources :users
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AdSpire
    = stylesheet_link_tag "application"  
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header#header.navbar
      .navbar-inner
        .container-fluid
          = link_to t(:company), 'http://www.adspire.nl', :class => 'brand'
          .pull-right
            -if !current_user.blank?
              = form_tag destroy_user_session_path, :method => :delete do
                .btn-group
                  = link_to current_user.email, edit_user_registration_path, :class => 'btn'
                  = link_to help_path, :class => 'btn btn-info' do
                    %i.icon-white.icon-info-sign
                    Help
                  %button{ :type => 'submit', :class => 'btn btn-danger' }
                    %i.icon-white.icon-off
            -else
              = link_to t(:login), new_user_session_path, :class => 'btn'
    #container.container-fluid
      #main.row-fluid
        %nav#nav-container.span2
          %ul#nav.nav.nav-pills.nav-stacked
            = active_link_to t(:dashboard), root_path, :wrap_tag => :li
            = active_link_to t('users.nav'), edit_user_registration_path, :wrap_tag => :li
            - if params['controller'] == 'users/registrations'
              %ul
                = active_link_to t(:edit_profile), edit_user_registration_path, :wrap_tag => :li
                = active_link_to t(:notifications), notifications_settings_path, :wrap_tag => :li
            = active_link_to t('feeds.nav'), feeds_path, :wrap_tag => :li
            - if params['controller'] == 'feeds'
              %ul
                = active_link_to t(:own_feeds), own_feeds_path, :wrap_tag => :li
                = active_link_to t(:all_feeds), feeds_path, :wrap_tag => :li
                = active_link_to t(:new_feed), new_feed_path, :wrap_tag => :li
            = active_link_to t(:sites), sites_path, :wrap_tag => :li
            - if params['controller'] == 'sites'
              %ul
                = active_link_to t(:all_sites), sites_path, :wrap_tag => :li
                = active_link_to t(:new_site), new_site_path, :wrap_tag => :li
        %section#content.span8
          - flash.each do |k, v|
            %div{ :id => k, :class => 'alert' }
              = v
          = yield
        %aside#notifications.span2
          %ul.nav.nav-list.well
            %li.nav-header
              .dropdown
                = link_to '#', :class => 'settings dropdown-toggle', 'data-toggle' => 'dropdown' do
                  %i.icon-cog
                %ul.dropdown-menu
                  %li
                    = link_to '#' do
                      Toggle notificaties
                  %li
                    = link_to '#' do
                      Notificatie instellingen
              Notificaties
            %li.divider
            - @notifications.each do |n|
              %li
                %button.remove
                  &times;
                = link_to('http://www.google.nl') do
                  = n.message  
                  %div.muted
                    = time_ago_in_words(n.created_at)
%footer
  %p
    = "© Adspire "+t = Time.now.strftime("%Y")